"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { isDemo, projectsApi, type Project } from "@/lib/projects-api";

type Message = { role: "user" | "assistant"; content: string; };
type Status = { ready: boolean; model: string; reason?: string; };
const examples = [
  { question: "Help me frame a research question", answer: "Illustrative example — not generated by AI.\n\nStart with a population, a situation, and an outcome:\n‘How do early-career researchers evaluate AI-generated summaries during a literature review?’\n\nNarrow the field and define what ‘evaluate’ means. A useful next step is to decide whether you want to observe behavior or interview participants." },
  { question: "Suggest a small study plan", answer: "Illustrative example — not generated by AI.\n\n1. Define one research question and the intended participants.\n2. Choose an interview or observation method.\n3. Draft a short protocol and pilot it.\n4. Plan consent and data handling before collecting anything.\n5. Identify limitations and how you will analyze the results.\n\nThis example does not use or cite uploaded documents." },
  { question: "What can this assistant access?", answer: "Illustrative example — not generated by AI.\n\nThe local assistant receives your recent conversation and, if selected, the project's name and description. It cannot read files, search the web, retrieve documents, or generate verified citations.\n\nOn your Mac, Go calls Ollama. This public demo only shows predefined examples; it makes no model requests." },
];

export function ResearchChat() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectID, setProjectID] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [draft, setDraft] = useState("");
  const [error, setError] = useState("");
  const [projectError, setProjectError] = useState("");
  const [status, setStatus] = useState<Status | null>(null);
  const [busy, setBusy] = useState(false);
  const [attempt, setAttempt] = useState(0);
  const active = useRef<AbortController | null>(null);
  const end = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const controller = new AbortController();
    projectsApi.list("active", controller.signal).then(result => { if (!controller.signal.aborted) setProjects(result.projects); }).catch(() => { if (!controller.signal.aborted) setProjectError("Project context could not be loaded. General chat is still available when the model is ready."); });
    if (!isDemo) fetch("/api/v1/ai/status", { signal: controller.signal, cache: "no-store" }).then(async r => { if (!r.ok) throw new Error(); return r.json(); }).then(value => { if (!controller.signal.aborted) setStatus(value); }).catch(() => { if (!controller.signal.aborted) setStatus({ ready: false, model: "", reason: "The Go API is unavailable. Start the local API and Ollama." }); });
    return () => controller.abort();
  }, [attempt]);
  useEffect(() => () => active.current?.abort(), []);
  useEffect(() => { end.current?.scrollIntoView({ block: "nearest", behavior: "smooth" }); }, [messages, busy]);

  async function send(event: FormEvent) {
    event.preventDefault();
    if (busy || active.current || !draft.trim() || !status?.ready || isDemo) return;
    const user: Message = { role: "user", content: draft.trim() };
    const history = messages.slice(-10);
    // Keep complete user/assistant pairs within the API's bounded character budget.
    while (history.length && history.reduce((n, m) => n + Array.from(m.content).length, Array.from(user.content).length) > 8000) history.splice(0, 2);
    const pending = [...history, user];
    const controller = new AbortController(); active.current = controller;
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/v1/ai/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: pending, ...(projectID ? { project_id: projectID } : {}) }), signal: AbortSignal.any([controller.signal, AbortSignal.timeout(130000)]) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error?.message ?? "Unable to generate a reply.");
      if (!controller.signal.aborted) { setMessages([...pending, result.message]); setDraft(""); if (result.truncated) setError("The reply reached its length limit. Ask a focused follow-up for more detail."); }
    } catch (err) {
      setError(controller.signal.aborted ? "Generation stopped. Your question is kept below." : err instanceof Error ? err.message : "Unable to generate a reply.");
    } finally { active.current = null; setBusy(false); }
  }

  return <>
    <main id="workspace" className="research-workspace projects-workspace chat-workspace" tabIndex={-1}>
      <div className="breadcrumb">Workspace / Research AI</div>
      <div className="projects-heading">
        <div>
          <h1>Research AI</h1>
          <p>A thinking partner for your next research question.</p>
        </div>
        <span className="tiny-badge">{isDemo ? "Scripted preview" : "Local AI"}</span>
      </div>
      <div className="chat-scope">
        <strong>{isDemo ? "Explore an example conversation" : "Your model, on your Mac"}</strong>
        <p>{isDemo ? "Choose a prompt below to see a predefined example. No AI model is running on this public website." : "Chat with Ollama through the Go API. Only recent messages and selected project metadata are sent to the local model. No documents or web search."}</p>
      </div>
      {!isDemo && <div className="chat-model" role="status">
        <span>{status ? status.ready ? `Ready · ${status.model}` : status.reason : "Checking local model…"}</span>
        <button className="secondary-button" disabled={busy} onClick={() => { setStatus(null); setProjectError(""); setAttempt(n => n + 1); }}>Check connection</button>
      </div>}
      <div className="chat-controls">
        <label htmlFor="chat-project">Project context<select id="chat-project" value={projectID} disabled={busy} onChange={e => { setProjectID(e.target.value); setMessages([]); setError(""); }}>
          <option value="">General research planning</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>
        </label>
        <button className="secondary-button" disabled={busy || messages.length === 0} onClick={() => { setMessages([]); setError(""); }}>New chat</button>
      </div>
      {projectError && <p className="field-help">{projectError}</p>}
      <p className="field-help">{isDemo ? "Project selection is illustrative; example replies are fixed." : "Context uses the project name and description only. Changing projects starts a new chat."}</p>
      <div className="chat-examples">{examples.map(example => <button key={example.question} className="secondary-button" disabled={busy} onClick={() => { if (isDemo) { setMessages([{ role: "user", content: example.question }, { role: "assistant", content: example.answer }]); setError(""); } else setDraft(example.question); }}>{example.question}</button>)}</div>
      <section className="chat-transcript" aria-label="Conversation" aria-live="polite" aria-busy={busy}>
        {!messages.length && <div className="chat-empty">
          <h2>Start with a question.</h2>
          <p>Explore an idea, shape a study, or discuss a research approach.</p>
        </div>}
        {messages.map((message, i) => <article key={i} className={`chat-message ${message.role}`}>
          <strong>{message.role === "user" ? "You" : isDemo ? "Example response" : "ResearchVault · Local AI"}</strong>
          <p>{message.content}</p>
        </article>)}
        {busy && <p role="status">Generating locally… First use may take longer while the model loads.</p>}
        <div ref={end} />
      </section>
      {error && <p role="alert" className="api-error">{error}</p>}
      <form className="chat-composer" onSubmit={send}>
        <label htmlFor="chat-question">{isDemo ? "Live chat is available in the local app" : "Your question"}</label>
        <textarea id="chat-question" value={draft} maxLength={2000} onChange={e => setDraft(e.target.value)} disabled={busy || isDemo} rows={3} placeholder={isDemo ? "Select an example above. Run locally to use a real model." : "Ask about your research…"} />
        <div className="form-actions">
          <span className="field-help">{isDemo ? "Predefined examples · No inference" : "Up to 2,000 characters · Recent 5 turns used as context"}</span>{busy ? <button className="secondary-button" type="button" onClick={event => { event.preventDefault(); active.current?.abort(); }}>Stop generating</button> : <button className="primary-button" disabled={isDemo || !status?.ready || !draft.trim()}>Send question</button>}</div>
      </form>
      <footer className="workspace-footer">
        <p>AI can be inaccurate. No document grounding or verified citations. Chat is not saved to the database and clears on reload. Use sample content only.</p>
      </footer>
    </main>
    <aside className="knowledge-panel project-context-panel">
      <div className="library-heading">
        <h2>Research context</h2>
      </div>
      <div className="source-principle">
        <h3>{projects.find(p => p.id === projectID)?.name ?? "General research planning"}</h3>
        <p>{projects.find(p => p.id === projectID)?.description ?? "Select a project to provide its name and description as background."}</p>
      </div>
      <div className="source-principle">
        <h3>Know the boundaries</h3>
        <p>This assistant cannot read files, search sources, or access your computer. Document retrieval and citations are not implemented.</p>
      </div>
      <div className="source-principle">
        <h3>How it works</h3>
        <p>{isDemo ? "This preview displays written examples. The companion Go repository contains the real Ollama integration." : "Next.js → Go → Ollama. The model runs on your Mac; there is no cloud-model fallback."}</p>
      </div>
    </aside>
  </>;
}
